# Common configuration shared between all applications
logging:
  level:
    ROOT: ERROR
    io.github.jhipster: INFO
    
configserver:
  name: Docker JHipster Registry 02
  status: Connected to the JHipster Registry running in Docker 02

jhipster:
  security: 
    authentication:
      jwt:
        secret: U3ByaW5nIENsb3VkIENvbmZpZ3VyYXRpb24=

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@jhipster-registry:8761/eureka/
